### ISSUE TITLE
Iron calculation in PaddedArmourRequiresBlackmetal.cs

### ISSUE THREAD

**Issue by Oedipvs** [OhhLoz/PaddedArmourRequiresBlackmetal#1]
You have calculations for upgrades as 

(N * 1f - PercentageBlackMetal.Value).  

Shouldn't that be 

(N * (1f - PercentageBlackMetal.Value)) ?

Right now with an "upgrade" config set to .66, upgrading helmets from 1 to 2 winds up costing 4 iron and 3 bm. Set it to .8, and you get 4 iron and 4 bm.  When the original recipe calls for only 5 metal pieces. That seems odd.

**Comment by OhhLoz** [comment]
You're right, I had the brackets correct in the normal calculation but omitted them in the upgrades for some reason. Thanks!
